### ISSUE TITLE
Increasing point generation for views with varying depths

### ISSUE THREAD

**Issue by KevinCain** [kwea123/CasMVSNet_pl#10]
Given [your approach to depth fusion](https://github.com/kwea123/CasMVSNet_pl/tree/master/evaluations) and my trials with 'CasMVSNet_pl', model completeness seems best when each view's range of depths falls within a global consensus range.

For example, in the case of DTU data, the depths contributed from each view are similar and the model completeness is quite good. However, when I use custom images with widely varying per-view depths, much of the total depth is truncated during point generation.

Do you have any advice for modifying depth fusion for greater completeness for scenes with intrinsically high depth, composed of photos for which depth varies greatly between views?

**Comment by kwea123** [comment]
With large varying depths, I first suspect that whether the depth image looks good before going to point generation. Currently the `depth_interval` is the same for all images, so it would not work if the depth ranges vary too much.

I would try to run the model twice, once with small `depth_interval` to get accurate depth for near objects (and also fusion), then with higher `depth_interval` to cover far objects, finally combine these two point clouds together.

**Comment by KevinCain** [comment]
Thanks @kwea123 for your helpful notes!

The depth limitations in plane-sweep stereo inherited by MVSNet variants can be a real problem for many data sets 'in the wild', especially of course for drone photography where scene depth can range enormously from one view to the next.

As you suggest, it is certainly possible to 'bracket' the depths from images, akin to assembling HDR images from LDR source. However, for very deep scenes this incurs a rather significant increase in time. That is, assuming 0-192 or 0-256 depth ranges, I find that for some source image we need five or more depth brackets to capture the image with reasonable fidelity.
