### ISSUE TITLE
testing on tanks datasets

### ISSUE THREAD

**Issue by chaytonmin** [kwea123/CasMVSNet_pl#12]
I find that the pair information of 99th images from the tanks advanced is None. How to solve the problem?

![捕获](https://user-images.githubusercontent.com/40260488/83231753-9aba9a00-a1be-11ea-81a2-4a4c507e8c2e.PNG)

**Comment by kwea123** [comment]
I manually added dummy data "98 0.0" to that line, so it looks like "0 98 0.0" after "99".
Since only this part is missing so I modified the file instead of handling with code.

**Comment by chaytonmin** [comment]
> I manually added dummy data "98 0.0" to that line, so it looks like "0 98 0.0" after "99".
> Since only this part is missing so I modified the file instead of handling with code.
> 
> Edit: this is "Temple" scene in case someone else has the same problem.

Got it!
