### ISSUE TITLE
Testing with colmap poses

### ISSUE THREAD

**Issue by cvgogogo** [kwea123/CasMVSNet_pl#13]
Hi kwea123 :)
I tried to use colmap poses to test scan9 in dtu dataset. In particular, I directly dropped images in scan9 into colmap and used outputs of colmap as the intrinsic and extrinsic parameters. The depth range is about 5 to 9. However in dtu the range is around 400 to 900. Unfortuantely, I got very bad results. I do not know where is the error. 
Do you have some suggestions ? 

By the way, I also wonder whether the performance is still acceptable with low texture objects.
Thank you very much.

**Comment by phongnhhn92** [comment]
I am not sure about this but it seems like the unit in DTU dataset is millimeters which means that you have to scale the colmap output with 100.

**Comment by cvgogogo** [comment]
> 
> 
> I am not sure about this but it seems like the unit in DTU dataset is millimeters which means that you have to scale the colmap output with 100.

Thanks, phongnhhn92. I wonder whether you have tried with successful camera data on scan9. if so, can you share with it ? thanks a lot~~~
