### ISSUE TITLE
Tanks results of casmvsnet_pl is worse than the original casmvsnet

### ISSUE THREAD

**Issue by chaytonmin** [kwea123/CasMVSNet_pl#14]
Tanks results of casmvsnet_pl is worse than the original casmvsnet(https://github.com/alibaba/cascade-stereo/tree/master/CasMVSNet). However, casmvsnet_pl has improved reconstruction performance on DTU dataset, why casmvsnet_pl  is worse than casmvsnet on Tanks dataset ?

**Comment by Todd-Qi** [comment]
Hi @kwea123 
Thanks for your great code!
Do you know the performance on *Tanks and Temples* benchmark if I train the CasMVSNet(_pl) on [BlendedMVS](https://github.com/YoYo000/BlendedMVS) dataset?

**Comment by kwea123** [comment]
@chaytonmin it still requires manual [depth range](https://github.com/kwea123/CasMVSNet_pl/blob/master/datasets/tanks.py#L42) tuning, which I just did not so carefully (cause my goal is not to get 1st place)
@Todd-Qi No, I didn't test. You can use my pretrained model to test.

**Comment by tatsy** [comment]
Hi @kwea123, thank you very much for sharing your depth range tuning data for Tanks and Temples.

Currently, I am testing the original CasMVSNet code to reproduce their results for T&T. After I used your depth ranges for the intermediate set (although it greatly improved the quality of the point clouds), I still got a very noisy point clouds particularly at background regions such as the sky in the Lighthouse image set (please see the image below).

<img width="989" alt="image" src="https://user-images.githubusercontent.com/1556493/102172984-5f26b980-3edd-11eb-8d2a-971b96c7182e.png">

If you know any workarounds to resolve this problem, could you share your experience with me, please?

**Comment by kwea123** [comment]
@tatsy maybe you can try to mask out the points that are too far from the camera? It is not included in the current code though

**Comment by tatsy** [comment]
@kwea123 Thank you very much for your advice. I just wanted to know what you did to achieve as good score as that provided in Cas-MVSNet paper. Did you do that masking based on camera positions?

Anyway, I will try that camera-based masking. Thank you.

**Comment by kwea123** [comment]
The score I get is exactly from the commands in https://github.com/kwea123/CasMVSNet_pl/tree/master/evaluations
And also details from https://github.com/kwea123/CasMVSNet_pl/releases/tag/v1.3
You can check if you get the same result using my pretrained model (normally you should)

**Comment by tatsy** [comment]
@kwea123 I am sorry that I missed the comment on the tag. This information is exactly what I wanted to know. Many repositories do not provide this kind of information (for Tanks & Temples), so I directly asked you before I tested by myself.

Again I am sorry that I made you unhappy due to my laziness. Thank you very much for your kindness!

**Comment by kwea123** [comment]
Hey don't feel sorry, I'm happy to provide solution for my code. Just maybe a bit late ;)
