### ISSUE TITLE
Fusing depth maps estimated for Tanks and Temples dataset on 2080Ti

### ISSUE THREAD

**Issue by Txusheng** [kwea123/CasMVSNet_pl#15]
Hi,
Thank you for your open-source code. CasMVSNet contributes a lot to the efficient multi-view depth estimation with limited GPU memory.

I am using the provided fusibile method to fuse full-resolution depth maps estimated for Tanks and Temples dataset. However, the fusion procedure breaks and seems to require more memories. 
Is there any way to fuse the depth maps with 11GB GPU ram for the Tanks and Temples dataset?

**Comment by kwea123** [comment]
I didn't have issue on my 2080Ti. When does the process break? Can you paste the console output?

**Comment by Txusheng** [comment]
I am sorry for opening the wrong issue. I mixed this project up with the official implementation which provides the Gipuma to fusion. The error occurs when using the Gipuma fusion. I am going to try your fusion method. I think it will work fine on 2080Ti.
