### ISSUE TITLE
Confidence map

### ISSUE THREAD

**Issue by phongnhhn92** [kwea123/CasMVSNet_pl#16]
Hi,
I see that in your code, you somehow collect the confidence map based on the predicted probability of depth. As I understand this probability tensor contains the probability for each sampled depth value along the ray for each pixel right ? Can u explain more what you have done to get this confidence map. Thanks !
https://github.com/kwea123/CasMVSNet_pl/blob/29a066d1e376099e84c1120d5156e3d10496680a/models/mvsnet.py#L176

**Comment by kwea123** [comment]
This is explained in the MVSNet [paper](https://arxiv.org/pdf/1804.02505.pdf) page 7. Intuitively if the model is confident, the distribution is centered at the predicted depth, so the value is high, otherwise the distribution is more spread and the value is low
