### ISSUE TITLE
Does this method work on real-captured images ?

### ISSUE THREAD

**Issue by phongnhhn92** [kwea123/CasMVSNet_pl#17]
Hi,
I am just wondering if I can use pretrained MVS or BlendMVS model on mobile phone captured images.
Also I wonder how can I get the poses as input to the network ? Please help me on this.

**Comment by kwea123** [comment]
Use colmap and `colmap2mvsnet.py` from [mvsnet](https://github.com/YoYo000/MVSNet#file-formats). I have successfully run the whole procedure on my own data once.

**Comment by phongnhhn92** [comment]
Hi,
I am just wondering why we would need to perform dense reconstruction to use MVS. I though we only need estimated poses and depth init value right ? Why would we need a mesh or pointcloud for ?

**Comment by kwea123** [comment]
It computes the **covisibility of points** to determine which views are close. The close views are then used as input to the network. If you can manually determine which views should be used together, you can perform only sparse reconstruction. Also in this case you need to write code for data loader by yourself. `colmap2mvsnet.py` only accept dense reconstruction.

**Comment by phongnhhn92** [comment]
Thanks a lot ! The script is very useful.
