### ISSUE TITLE
Choosing depth interval for Tanks and Temples dataset

### ISSUE THREAD

**Issue by phongnhhn92** [kwea123/CasMVSNet_pl#18]
Hi, 
1) I wonder if u have trained your model on Tanks and Temples dataset. I have read your dataloader on this dataset for evaluation's purposes but I see that you hand-tuned the depth interval for each scene for the best results I guess.  However, I am writing my own dataloader on this dataset and I wonder how to choose optimal depth_interval value for the whole dataset for training ? 
I know it is possible to use different depth_interval for each scene but does it work though ?

2) I see that in the BlendMVS dataloader you are [scaling](https://github.com/kwea123/CasMVSNet_pl/blob/29a066d1e376099e84c1120d5156e3d10496680a/datasets/blendedmvs.py#L100) the depth_min value. I wonder should I do something like that with Tanks and Temples dataset ? I check a few cam file and I see these depth_min value are quite similar (0.04 ~ 1.99) and it's not like BlendMVS dataset but just wanna ask to make sure.

**Comment by kwea123** [comment]
1. No I didn't trained on Tanks and Temples. I use model trained on DTU to evaluate. You need to try by yourself.
2. Scaling is not necessary to training and won't affect performance, but scaling them to roughly the same range as DTU has several benefits as stated [here](https://github.com/kwea123/CasMVSNet_pl#some-modifications-wrt-original-paper)

**Comment by phongnhhn92** [comment]
Thanks !
