### ISSUE TITLE
About the time of forward inference

### ISSUE THREAD

**Issue by Todd-Qi** [kwea123/CasMVSNet_pl#19]
Hi, thanks for your great code!
When using PyTorch-lightning, is the running time getting faster?

**Comment by kwea123** [comment]
Hi, at **inference** it has nothing to do with pytorch lightning, pytorch lightning is only used at **training**, so the inference speed shouldn't change much w.r.t the original implementation. As for training, if I remember correctly, it also runs at the same speed.
