### ISSUE TITLE
About the Inplace-ABN

### ISSUE THREAD

**Issue by Todd-Qi** [kwea123/CasMVSNet_pl#20]
Hi, thanks for sharing the code tricks!
As you say, the GPU memory is reducing about 15% when we replace `BN+ReLU`  with `Inplace-ABN`. 
I wonder to know that it works only during *training*, **or** both the *training* and *testing*.

Looking forward to your reply.
Many Thanks!!!

**Comment by kwea123** [comment]
It works only for training, the main contribution is that it reduces the buffer required for **backward pass**. An [explanation](https://medium.com/@eugenekhvedchenya/why-you-should-start-using-in-place-activated-batchnorm-11a85bb15c06)
