### ISSUE TITLE
自采数据深度图估计效果很差

### ISSUE THREAD

**Issue by aweijx** [kwea123/CasMVSNet_pl#21]
@kwea123 你好，很感谢你的开源，我用手机自采数据并用colmap稀疏重建去畸变后得到了相机参数，再用yaoyao提供的转换代码[https://github.com/YoYo000/MVSNet/blob/master/mvsnet/colmap2mvsnet.py](url)得到网络可用的输入。
但最终重建效果很差。
以下分别是原图、深度图、融合的点云：
![原图](https://user-images.githubusercontent.com/49384093/95848827-26ede800-0d81-11eb-8e8e-4c2877f8e632.jpg)![深度图](https://user-images.githubusercontent.com/49384093/95848716-002fb180-0d81-11eb-8183-3ffe483b393a.png)![点云](https://user-images.githubusercontent.com/49384093/95849176-b1364c00-0d81-11eb-8453-6b3a09ad7d90.png)
想请问：
1、用colmap稀疏重建时是否要改动参数（我用的默认参数）
2、colmap2mvsnet转化出来的相机参数明显有问题（深度范围？）
3、用casmvsnet进行深度估计时我是改动的tanks.py的数据入口（路径之类的改动），选取的depth_interval参数为1.5e-2，重建出来点云大概在2、3M左右，而dtu、belended数据集重建都在20M以上

**Comment by kwea123** [comment]
看起來深度估計並不是完全不對，所以我認為是2. 3.的深度範圍設定有誤
你用colmap gui看看是否背景的點也有被重建出來，如果有那可以嘗試手動減小max depth來去除背景的影響
然後depth interval的部份，最好設定成depth_interval = (depth_max-depth_min)/192 來保證全部的範圍都有被sample

**Comment by aweijx** [comment]
谢谢你的解答 @kwea123 ，这是用35张图生成的12.96M点云结果：
![2020-10-15 14-48-42屏幕截图](https://user-images.githubusercontent.com/49384093/96086970-b2888580-0ef5-11eb-881e-6bd5c965ead9.png)
但经过测试，不论是自采数据还是经过colmap转化后的dtu、tanks数据，depth_interval参数设定在0.015左右总能得到更好的结果。我还有两点疑问：
1.你在tanks.py中手动设定了depth_interval参数，能问它们是如何确定的吗？
2.若按depth_interval = (depth_max-depth_min)/192设定，其中的depth_max与depth_min是指所有视图的最大depth_max和最小depth_min吗？

**Comment by kwea123** [comment]
1. 我是手動慢慢調，例如我先試1e-3，覺得效果不好再試1e-2，然後調到我覺得結果可以。
2. 如果要cover全部的圖的話，要設定成max (depth_max-depth_min)/192。你寫的是(max(depth_max)-min(depth_min))/192，雖然我覺得值應該差不多?如果每張圖的depth max跟depth min沒有太大差異。

我覺得你圖中的點雲看起來已經不錯了，手動慢慢調depth interval應該就可以

**Comment by aweijx** [comment]
非常感谢@kwea123

**Comment by DMJ1997** [comment]
你好，我也在尝试用自采数据进行测试，colmap undistortion、stereo之后，进行fusion时程序崩溃 segmentation fault。请问你是怎么操作的，搭建的环境配置是什么？

**Comment by kwea123** [comment]
COLMAP的问题可以在https://github.com/colmap/colmap下面寻找或发问。

**Comment by Mizodesu** [comment]
你好，在转换相机参数时，转换完成后 和dtu数据集上的 格式是有差异的，这个转换的代码是需要自己修改的嘛？ 如果是 可否分享一下您的心得呢@aweijx

**Comment by djwknight** [comment]
你好，是用yaoyao提供的转换代码跑.log文件吗

**Comment by Arwen831** [comment]
> 你好，在转换相机参数时，转换完成后 和dtu数据集上的 格式是有差异的，这个转换的代码是需要自己修改的嘛？ 如果是 可否分享一下您的心得呢@aweijx

请问您解决格式有异的问题了嘛？如果解决了能否指导一下，感谢！

**Comment by aweijx** [comment]
> 你好，在转换相机参数时，转换完成后 和dtu数据集上的 格式是有差异的，这个转换的代码是需要自己修改的嘛？ 如果是 可否分享一下您的心得呢@aweijx

转化得到的相机参数格式没有什么太大区别，重点要修改数据输入文件(可以在tanks.py基础上进行路径之类的改动)，估计深度时depth_interval这个参数非常重要，一般可以先设置为0.02左右看看效果，如果没有太大问题再进行微调。
此外，最终点云效果好不好主要还是看拍摄的图片质量(图片重叠度高，数量多，表面都能覆盖到的话效果就好)以及深度图过滤融合(confidence，min_geo_consistent这两个参数可以多试试，输入图片少的情况下conf设置比较高的话生成的点云就会比较少，重建表面会有空洞，可以尝试设置低一点。min_geo_consistent设置高一点也会生成更多的点，但相对的会有更多噪点)

**Comment by Zhanchenhaha** [comment]
> @kwea123 你好，很感谢你的开源，我用手机自采数据并用colmap稀疏重建去畸变后得到了相机参数，再用yaoyao提供的转换代码[https://github.com/YoYo000/MVSNet/blob/master/mvsnet/colmap2mvsnet.py](url)得到网络可用的输入。 但最终重建效果很差。 以下分别是原图、深度图、融合的点云： ![原图](https://user-images.githubusercontent.com/49384093/95848827-26ede800-0d81-11eb-8e8e-4c2877f8e632.jpg)![深度图](https://user-images.githubusercontent.com/49384093/95848716-002fb180-0d81-11eb-8183-3ffe483b393a.png)![点云](https://user-images.githubusercontent.com/49384093/95849176-b1364c00-0d81-11eb-8453-6b3a09ad7d90.png) 想请问： 1、用colmap稀疏重建时是否要改动参数（我用的默认参数） 2、colmap2mvsnet转化出来的相机参数明显有问题（深度范围？） 3、用casmvsnet进行深度估计时我是改动的tanks.py的数据入口（路径之类的改动），选取的depth_interval参数为1.5e-2，重建出来点云大概在2、3M左右，而dtu、belended数据集重建都在20M以上
你好我想问一下我自己拍摄了一写照片，使用gui导入，重建时没有内容，我想问一下在使用gui时相机位置（.db文件）怎么生成

**Comment by fanshixiong** [comment]
@kwea123 @aweijx  @Zhanchenhaha @Mizodesu  您好，我用colmap稀疏重建后跑MVSNet，得到的深度范围一直是6-8，最后估计的深度图也不对，重建点云很少，效果很差，这个深度范围应该怎么修改呢？

**Comment by Shallowing** [comment]
@fanshixiong 我遇到了和您一样的问题，请问您最后是怎么解决的呢？
