### ISSUE TITLE
About Homography Warping

### ISSUE THREAD

**Issue by GONGYue1231** [kwea123/CasMVSNet_pl#23]
Hi, i find the implemented homo_warp different with fomula referenced in the paper and hard to proof those two to be mathmatically equal:
code:
![image](https://user-images.githubusercontent.com/47766482/103129234-fc020780-46d2-11eb-9674-67ade4940d0f.png)

formula:
![image](https://user-images.githubusercontent.com/47766482/103129199-decd3900-46d2-11eb-8ea2-8173569db644.png)

Could you please give a reference algorithm of your code implementation?

**Comment by kwea123** [comment]
If you understand Chinese you can see here: https://github.com/YoYo000/MVSNet/issues/77
Actually his formula is wrong. You need to consider backprojection and reprojection separately

**Comment by phongnhhn92** [comment]
@kwea123 Hi, can you please explain this in English ? I am curious as well. What is wrong about this Eqn(1) in MVS paper ?
