### ISSUE TITLE
About Inplace-abn

### ISSUE THREAD

**Issue by Tangshengku** [kwea123/CasMVSNet_pl#24]
Excellent work! 
I notice during the training, you used the 'from inplace-abn import InPlaceABN' but in test, it turns to 'from inplace-abn import ABN'. Is there any difference between these two kinds?

**Comment by kwea123** [comment]
For training use inplace-abn to save the (intermediate) memory, but for testing use ABN (normal batch normalization+activation) to increase the speed. The output is the same.
