### ISSUE TITLE
How should we test the model on ETH3D dataset？

### ISSUE THREAD

**Issue by NoOneUST** [kwea123/CasMVSNet_pl#26]
I only find the dataset file for DTU and Blended, can we test the model on ETH3D? I also have not found such file in other pytorch implements Of MVSNet-based methods.

**Comment by kwea123** [comment]
I didn't try ETH3D at all. You can refer to the py files in the datasets folder to get an idea of how to convert ETH3D to the network inputs. It shouldn't be that difficult.
