### ISSUE TITLE
How to remove the InplaceABN part

### ISSUE THREAD

**Issue by NoOneUST** [kwea123/CasMVSNet_pl#27]
I have problems compiling the InplaceABN module, and I find that with InplaceABN, the Pytorch version is bounded. Thus, I want to remove the InplaceABN module and use half-precision to replace it. How should I do? Thank you~

**Comment by kwea123** [comment]
First I don't think InplaceABN bounds the pytorch version, if you install the latest version, it should be downward compatible.

If you really want to replace InplaceABN, just replace it with a sequential bachnorm+relu, it should be easy.
