### ISSUE TITLE
small mistakes in /datasets/tanks.py I think

### ISSUE THREAD

**Issue by LuckyOne09** [kwea123/CasMVSNet_pl#28]
Hi, first of all, THANKS a lot for your excellent work.
but I think there are some mistakes when loading data from TanksDataset.
line 68 in tanks.py should be:  ``` with open(os.path.join(self.root_dir, self.split, scan, 'pair.txt')) as f: ```
line 82 in tanks.py should be:  ``` proj_mat_filename = os.path.join(self.root_dir, self.split, scan,
                                                 f'cams/{vid:08d}_cam.txt') ```
line 132 in tanks.py should be: ``` img_filename = os.path.join(self.root_dir, self.split, scan, f'images/{vid:08d}.jpg') ```

In one word: I feel like you miss ```self.split``` when load data from TanksDataset.

**Comment by LuckyOne09** [comment]
I guess your root_dir used in evaluation process of tanksandtemple is /tankandtemples/advanced or /tankandtemples/intermediate. If so, that's right.

**Comment by kwea123** [comment]
Yes, you are correct. The `split` should be in the path. I fixed it.

**Comment by LuckyOne09** [comment]
Thank you for your reply. And I have an another question about class TanksDataset now. How do you choose depth_interval for each scan? You just use brute-force search or you have some references about it?

**Comment by kwea123** [comment]
I manually tuned it until I get visually plausible results. There is no reference, so it's highly probable that these values are not optimal.

**Comment by LuckyOne09** [comment]
Thank you for your quick response. I found that the author of MVSNet mentioned the camera files format here (https://github.com/YoYo000/MVSNet/blob/master/README.md#camera-files)
I guess the DEPTH_INTERVAL in the camera file could be a hint to specify the appropriate depth_interval.
