### ISSUE TITLE
Pretrained BlendedMVS model

### ISSUE THREAD

**Issue by KevinCain** [kwea123/CasMVSNet_pl#3]
@kwea123, your results trained with BlendedMVS look enticing -- is your model available for download? Perhaps I'm missing something in plain sight...

Also, if you have a moment can you confirm that you used Yao Yao's large image set when training? Any training notes would be wonderful.

Thanks again,

-Kevin

**Comment by kwea123** [comment]
There is one model trained on DTU available for download. The result I get is generated from another model (also trained on DTU, which I won't provide to keep release clean) but you should get similar performance with the model I provide.

Until now everything is trained on DTU. I have finished the training code for BlendedMVS but I haven't had time to actually train on it; I plan to release the code once I finished training and provide a model on BlendedMVS as well. As for the training image, I will use the default 768x576 (small) resolution to train and 2048x1536 (large) resolution to test as done in the paper.

**Comment by KevinCain** [comment]
Thanks @kwea123 for this helpful clarification. Let me know if I can help!
