### ISSUE TITLE
Point cloud is worse than original project on DTU

### ISSUE THREAD

**Issue by YuhsiHu** [kwea123/CasMVSNet_pl#37]
Hi, thank you for your code!
I run your pre-trained model on DTU dataset but the point cloud is not as complete as that the original project generated.
![image](https://user-images.githubusercontent.com/34529345/124895486-2b44ea00-e00f-11eb-80af-9c31f2a7e515.png)
![image](https://user-images.githubusercontent.com/34529345/124895639-4f083000-e00f-11eb-9777-ee2ff715467b.png)

**Comment by kwea123** [comment]
Please give more details, what pretrained model do you use and what eval command do you use?
I just reran `python eval.py --dataset_name dtu --scan scan1` with this model https://github.com/kwea123/CasMVSNet_pl/releases/tag/v1.0
and this is what I got 
![Screenshot from 2021-07-08 20-53-06](https://user-images.githubusercontent.com/11364490/124917253-8c2fea80-e02e-11eb-868d-fb6414c0f873.png)
It contains 29.44 M points. I don't see any problem.

**Comment by YuhsiHu** [comment]
Yes, I use your pre-trained model from the url you post: _ckpt_epoch_10.ckpt. 
And I use this command: 
python eval.py \
  --root_dir $DTUTESTPATH \
  --dataset_name dtu \
  --split test \
  --ckpt_path $CKPT_FILE

The scan1's point cloud file I get is 238M(16.66M points), which is smaller than that I got from original project(418M).
What should I do to generate 29.44M points?
Thank you for your time!

**Comment by kwea123** [comment]
It is strange, do you use the latest master code? Also please make sure python=3.7, and all the package version is the same as in `requirements.txt`.
Other than that, I don't know what the reason is. There is no randomness in the algorithm...

**Comment by YuhsiHu** [comment]
In order to keep the version consistent, I did not use RTX3090. I use 2080ti.
I did use python 3.7, and cudatoolkit==10.1, cudnn==8.0.5, pytorch==1.7.1, torchvision==0.8.2(0.5.0 will report error). And other packages are the same as requirements.

It is strange. I will test it on other machines and once there are new results, I will give feedback in time.
Thank you again for your prompt reply.

**Comment by kwea123** [comment]
I think GPU is not a problem. In the readme pytorch==1.4.0, can you try using this version?

**Comment by YuhsiHu** [comment]
I tried pytorch==1.4.0, the result is the same as pytorch==1.7.1,the point cloud file of scan1 is 238M.

**Comment by kwea123** [comment]
Didn't you change some default parameters by chance? Can you post your `eval.py`?

**Comment by YuhsiHu** [comment]
from datasets import dataset_dict
from datasets.utils import save_pfm, read_pfm
import cv2
import torch
import os, shutil
import numpy as np
from tqdm import tqdm
from argparse import ArgumentParser

# for depth prediction
from models.mvsnet import CascadeMVSNet
from utils import load_ckpt
from inplace_abn import ABN

# for point cloud fusion
from numba import jit
from plyfile import PlyData, PlyElement

torch.backends.cudnn.benchmark = True  # this increases inference speed a little


def get_opts():
    parser = ArgumentParser()
    parser.add_argument('--root_dir', type=str,
                        default='/home/ubuntu/data/DTU/mvs_training/dtu/',
                        help='root directory of dtu dataset')
    parser.add_argument('--dataset_name', type=str, default='dtu',
                        choices=['dtu', 'tanks', 'blendedmvs'],
                        help='which dataset to train/val')
    parser.add_argument('--split', type=str, default='test',
                        help='which split to evaluate')
    parser.add_argument('--scan', type=str, default='',
                        help='specify scan to evaluate (must be in the split)')
    parser.add_argument('--cpu', default=False, action='store_true',
                        help='''use cpu to do depth inference.
                                WARNING: It is going to be EXTREMELY SLOW!
                                about 37s/view, so in total 30min/scan. 
                             ''')
    # for depth prediction
    parser.add_argument('--n_views', type=int, default=5,
                        help='number of views (including ref) to be used in testing')
    parser.add_argument('--depth_interval', type=float, default=2.65,
                        help='depth interval unit in mm')
    parser.add_argument('--n_depths', nargs='+', type=int, default=[8, 32, 48],
                        help='number of depths in each level')
    parser.add_argument('--interval_ratios', nargs='+', type=float, default=[1.0, 2.0, 4.0],
                        help='depth interval ratio to multiply with --depth_interval in each level')
    parser.add_argument('--num_groups', type=int, default=1, choices=[1, 2, 4, 8],
                        help='number of groups in groupwise correlation, must be a divisor of 8')
    parser.add_argument('--img_wh', nargs="+", type=int, default=[1152, 864],
                        help='resolution (img_w, img_h) of the image, must be multiples of 32')
    parser.add_argument('--ckpt_path', type=str, default='ckpts/exp2/_ckpt_epoch_10.ckpt',
                        help='pretrained checkpoint path to load')
    parser.add_argument('--save_visual', default=False, action='store_true',
                        help='save depth and proba visualization or not')

    # for point cloud fusion
    parser.add_argument('--conf', type=float, default=0.999,
                        help='min confidence for pixel to be valid')
    parser.add_argument('--min_geo_consistent', type=int, default=5,
                        help='min number of consistent views for pixel to be valid')
    parser.add_argument('--max_ref_views', type=int, default=400,
                        help='max number of ref views (to limit RAM usage)')
    parser.add_argument('--skip', type=int, default=1,
                        help='''how many points to skip when creating the point cloud.
                                Larger = fewer points and smaller file size.
                                Ref: skip=10 creates ~= 3M points = 50MB file
                                     skip=1 creates ~= 30M points = 500MB file
                             ''')

    return parser.parse_args()


def decode_batch(batch):
    imgs = batch['imgs']
    proj_mats = batch['proj_mats']
    init_depth_min = batch['init_depth_min'].item()
    depth_interval = batch['depth_interval'].item()
    scan, vid = batch['scan_vid']
    return imgs, proj_mats, init_depth_min, depth_interval, \
           scan, vid


# define read_image and read_proj_mat for each dataset

def read_image(dataset_name, root_dir, scan, vid):
    if dataset_name == 'dtu':
        return cv2.imread(os.path.join(root_dir,
                                       f'Rectified/{scan}/rect_{vid + 1:03d}_3_r5000.png'))
    if dataset_name == 'tanks':
        return cv2.imread(os.path.join(root_dir, scan,
                                       f'images/{vid:08d}.jpg'))
    if dataset_name == 'blendedmvs':
        return cv2.imread(os.path.join(root_dir, scan,
                                       f'blended_images/{vid:08d}.jpg'))


def read_refined_image(dataset_name, scan, vid):
    return cv2.imread(f'results/{dataset_name}/image_refined/{scan}/{vid:08d}.png')


def save_refined_image(image_refined, dataset_name, scan, vid):
    cv2.imwrite(f'results/{dataset_name}/image_refined/{scan}/{vid:08d}.png',
                image_refined)


def read_proj_mat(dataset_name, dataset, scan, vid):
    if dataset_name == 'dtu':
        return dataset.proj_mats[vid][0][0].numpy()
    if dataset_name in ['tanks', 'blendedmvs']:
        return dataset.proj_mats[scan][vid][0][0].numpy()


@jit(nopython=True, fastmath=True)
def xy_ref2src(xy_ref, depth_ref, P_world2ref,
               depth_src, P_world2src, img_wh):
    # create ref grid and project to ref 3d coordinate using depth_ref
    xyz_ref = np.vstack((xy_ref, np.ones_like(xy_ref[:1]))) * depth_ref
    xyz_ref_h = np.vstack((xyz_ref, np.ones_like(xy_ref[:1])))

    P = (P_world2src @ np.ascontiguousarray(np.linalg.inv(P_world2ref)))[:3]
    # project to src 3d coordinate using P_world2ref and P_world2src
    xyz_src_h = P @ xyz_ref_h.reshape(4, -1)
    xy_src = xyz_src_h[:2] / xyz_src_h[2:3]
    xy_src = xy_src.reshape(2, img_wh[1], img_wh[0])

    return xy_src


@jit(nopython=True, fastmath=True)
def xy_src2ref(xy_ref, xy_src, depth_ref, P_world2ref,
               depth_src2ref, P_world2src, img_wh):
    # project xy_src back to ref view using the sampled depth
    xyz_src = np.vstack((xy_src, np.ones_like(xy_src[:1]))) * depth_src2ref
    xyz_src_h = np.vstack((xyz_src, np.ones_like(xy_src[:1])))
    P = (P_world2ref @ np.ascontiguousarray(np.linalg.inv(P_world2src)))[:3]
    xyz_ref_h = P @ xyz_src_h.reshape(4, -1)
    depth_ref_reproj = xyz_ref_h[2].reshape(img_wh[1], img_wh[0])
    xy_ref_reproj = xyz_ref_h[:2] / xyz_ref_h[2:3]
    xy_ref_reproj = xy_ref_reproj.reshape(2, img_wh[1], img_wh[0])

    # check |p_reproj-p_1| < 1
    pixel_diff = xy_ref_reproj - xy_ref
    mask_pixel_reproj = (pixel_diff[0] ** 2 + pixel_diff[1] ** 2) < 1

    # check |d_reproj-d_1| / d_1 < 0.01
    mask_depth_reproj = np.abs((depth_ref_reproj - depth_ref) / depth_ref) < 0.01

    mask_geo = mask_pixel_reproj & mask_depth_reproj

    return depth_ref_reproj, mask_geo


def check_geo_consistency(depth_ref, P_world2ref,
                          depth_src, P_world2src,
                          image_ref, image_src,
                          img_wh):
    """
    Check the geometric consistency between ref and src views.
    """
    xy_ref = np.mgrid[:img_wh[1], :img_wh[0]][::-1].astype(np.float32)
    xy_src = xy_ref2src(xy_ref, depth_ref, P_world2ref,
                        depth_src, P_world2src, img_wh)

    # Sample the depth of xy_src using bilinear interpolation
    depth_src2ref = cv2.remap(depth_src,
                              xy_src[0].astype(np.float32),
                              xy_src[1].astype(np.float32),
                              interpolation=cv2.INTER_LINEAR)

    image_src2ref = cv2.remap(image_src,
                              xy_src[0].astype(np.float32),
                              xy_src[1].astype(np.float32),
                              interpolation=cv2.INTER_LINEAR)

    depth_ref_reproj, mask_geo = \
        xy_src2ref(xy_ref, xy_src, depth_ref, P_world2ref,
                   depth_src2ref, P_world2src, img_wh)

    depth_ref_reproj[~mask_geo] = 0
    image_src2ref[~mask_geo] = 0

    return depth_ref_reproj, mask_geo, image_src2ref


if __name__ == "__main__":
    args = get_opts()
    dataset = dataset_dict[args.dataset_name] \
        (args.root_dir, args.split,
         n_views=args.n_views, depth_interval=args.depth_interval,
         img_wh=tuple(args.img_wh))

    if args.scan:
        scans = [args.scan]
    else:  # evaluate on all scans in dataset
        scans = dataset.scans

    # Step 1. Create depth estimation and probability for each scan
    model = CascadeMVSNet(n_depths=args.n_depths,
                          interval_ratios=args.interval_ratios,
                          num_groups=args.num_groups,
                          norm_act=ABN)
    device = 'cpu' if args.cpu else 'cuda:0'
    model.to(device)
    load_ckpt(model, args.ckpt_path)
    model.eval()

    depth_dir = f'results/{args.dataset_name}/depth'
    print('Creating depth and confidence predictions...')
    if args.scan:
        data_range = [i for i, x in enumerate(dataset.metas) if x[0] == args.scan]
    else:
        data_range = range(len(dataset))
    for i in tqdm(data_range):
        imgs, proj_mats, init_depth_min, depth_interval, \
        scan, vid = decode_batch(dataset[i])

        os.makedirs(os.path.join(depth_dir, scan), exist_ok=True)

        with torch.no_grad():
            imgs = imgs.unsqueeze(0).to(device)
            proj_mats = proj_mats.unsqueeze(0).to(device)
            results = model(imgs, proj_mats, init_depth_min, depth_interval)

        depth = results['depth_0'][0].cpu().numpy()
        depth = np.nan_to_num(depth)  # change nan to 0
        proba = results['confidence_2'][0].cpu().numpy()  # NOTE: this is 1/4 scale!
        proba = np.nan_to_num(proba)  # change nan to 0
        save_pfm(os.path.join(depth_dir, f'{scan}/depth_{vid:04d}.pfm'), depth)
        save_pfm(os.path.join(depth_dir, f'{scan}/proba_{vid:04d}.pfm'), proba)
        if args.save_visual:
            mi = np.min(depth[depth > 0])
            ma = np.max(depth)
            depth = (depth - mi) / (ma - mi + 1e-8)
            depth = (255 * depth).astype(np.uint8)
            depth_img = cv2.applyColorMap(depth, cv2.COLORMAP_JET)
            cv2.imwrite(os.path.join(depth_dir, f'{scan}/depth_visual_{vid:04d}.jpg'),
                        depth_img)
            cv2.imwrite(os.path.join(depth_dir, f'{scan}/proba_visual_{vid:04d}.jpg'),
                        (255 * (proba > args.conf)).astype(np.uint8))
        del imgs, proj_mats, results
    del model
    torch.cuda.empty_cache()
    ###################################################################################

    # Step 2. Perform depth filtering and fusion
    point_dir = f'results/{args.dataset_name}/points'
    os.makedirs(point_dir, exist_ok=True)
    print('Fusing point clouds...')

    for scan in scans:
        print(f'Processing {scan} ...')
        # buffers for the final vertices of this scan
        vs = []
        v_colors = []
        # buffers storing the refined data of each ref view
        os.makedirs(f'results/{args.dataset_name}/image_refined/{scan}', exist_ok=True)
        image_refined = set()
        depth_refined = {}
        for meta in tqdm(list(filter(lambda x: x[0] == scan, dataset.metas))[:args.max_ref_views]):
            try:
                ref_vid = meta[2]
                if ref_vid in image_refined:  # not yet refined actually
                    image_ref = read_refined_image(args.dataset_name, scan, ref_vid)
                    depth_ref = depth_refined[ref_vid]
                else:
                    image_ref = read_image(args.dataset_name, args.root_dir, scan, ref_vid)
                    #
                    print(args.dataset_name, args.root_dir, scan, ref_vid)
                    image_ref = cv2.resize(image_ref, tuple(args.img_wh), interpolation=cv2.INTER_LINEAR)[:, :, ::-1]  # to RGB
                    depth_ref = read_pfm(f'results/{args.dataset_name}/depth/' \
                                         f'{scan}/depth_{ref_vid:04d}.pfm')[0]
                proba_ref = read_pfm(f'results/{args.dataset_name}/depth/' \
                                     f'{scan}/proba_{ref_vid:04d}.pfm')[0]
                proba_ref = cv2.resize(proba_ref, None, fx=4, fy=4,
                                       interpolation=cv2.INTER_LINEAR)
                mask_conf = proba_ref > args.conf  # confidence mask
                P_world2ref = read_proj_mat(args.dataset_name, dataset, scan, ref_vid)

                src_vids = meta[3]
                mask_geos = []
                depth_ref_reprojs = [depth_ref]
                image_src2refs = [image_ref]
                # for each src view, check the consistency and refine depth
                for src_vid in src_vids:
                    if src_vid in image_refined:  # use refined data of previous runs
                        image_src = read_refined_image(args.dataset_name, scan, src_vid)
                        depth_src = depth_refined[src_vid]
                    else:
                        image_src = read_image(args.dataset_name, args.root_dir, scan, src_vid)
                        image_src = cv2.resize(image_src, tuple(args.img_wh),
                                               interpolation=cv2.INTER_LINEAR)[:, :, ::-1]  # to RGB
                        depth_src = read_pfm(f'results/{args.dataset_name}/depth/' \
                                             f'{scan}/depth_{src_vid:04d}.pfm')[0]
                        depth_refined[src_vid] = depth_src
                    P_world2src = read_proj_mat(args.dataset_name, dataset, scan, src_vid)
                    depth_ref_reproj, mask_geo, image_src2ref = \
                        check_geo_consistency(depth_ref, P_world2ref,
                                              depth_src, P_world2src,
                                              image_ref, image_src, tuple(args.img_wh))
                    depth_ref_reprojs += [depth_ref_reproj]
                    image_src2refs += [image_src2ref]
                    mask_geos += [mask_geo]
                mask_geo_sum = np.sum(mask_geos, 0)
                mask_geo_final = mask_geo_sum >= args.min_geo_consistent
                depth_refined[ref_vid] = \
                    (np.sum(depth_ref_reprojs, 0) / (mask_geo_sum + 1)).astype(np.float32)
                image_refined_ = \
                    np.sum(image_src2refs, 0) / np.expand_dims((mask_geo_sum + 1), -1)

                image_refined.add(ref_vid)
                save_refined_image(image_refined_, args.dataset_name, scan, ref_vid)
                mask_final = mask_conf & mask_geo_final

                # create the final points
                xy_ref = np.mgrid[:args.img_wh[1], :args.img_wh[0]][::-1]
                xyz_ref = np.vstack((xy_ref, np.ones_like(xy_ref[:1]))) * depth_refined[ref_vid]
                xyz_ref = xyz_ref.transpose(1, 2, 0)[mask_final].T  # (3, N)
                color = image_refined_[mask_final]  # (N, 3)
                xyz_ref_h = np.vstack((xyz_ref, np.ones_like(xyz_ref[:1])))
                xyz_world = (np.linalg.inv(P_world2ref) @ xyz_ref_h).T  # (N, 4)
                xyz_world = xyz_world[::args.skip, :3]
                color = color[::args.skip]

                # append to buffers
                vs += [xyz_world]
                v_colors += [color]

            except FileNotFoundError:
                # some scenes might not have depth prediction due to too few valid src views
                print(f'Skipping view {ref_vid} due to too few valid source views...')
                continue

        # clear refined buffer
        image_refined.clear()
        depth_refined.clear()
        shutil.rmtree(f'results/{args.dataset_name}/image_refined/{scan}')

        # process all points in the buffers
        vs = np.ascontiguousarray(np.vstack(vs).astype(np.float32))
        v_colors = np.vstack(v_colors).astype(np.uint8)
        print(f'{scan} contains {len(vs) / 1e6:.2f} M points')
        vs.dtype = [('x', 'f4'), ('y', 'f4'), ('z', 'f4')]
        v_colors.dtype = [('red', 'u1'), ('green', 'u1'), ('blue', 'u1')]

        vertex_all = np.empty(len(vs), vs.dtype.descr + v_colors.dtype.descr)
        for prop in vs.dtype.names:
            vertex_all[prop] = vs[prop][:, 0]
        for prop in v_colors.dtype.names:
            vertex_all[prop] = v_colors[prop][:, 0]

        el = PlyElement.describe(vertex_all, 'vertex')
        PlyData([el]).write(f'{point_dir}/{scan}.ply')
        del vertex_all, vs, v_colors
    shutil.rmtree(f'results/{args.dataset_name}/image_refined')

    print('Done!')

**Comment by kwea123** [comment]
Hmm, your `eval.py` looks good, and I used it and got the correct result (29.44M points).
I had another thought. How about setting `torch.backends.cudnn.benchmark = False` at line 19? This flag also introduces some randomness.

**Comment by YuhsiHu** [comment]
It’s a pity that it didn’t work.

**Comment by kwea123** [comment]
Can you add `--save_visual` argument? It will save the visual depth. I want to make sure it looks the same.
This is my `depth_visual_0000.jpg`.
![depth_visual_0000](https://user-images.githubusercontent.com/11364490/125084384-6d9c2300-e104-11eb-955c-9461f152be69.jpg)

**Comment by YuhsiHu** [comment]
It is strange that they are different. I did download the latest version of the code.
![depth_visual_0000](https://user-images.githubusercontent.com/34529345/125196379-5425e300-e28c-11eb-8d23-3b3f94d48f99.jpg)
![image](https://user-images.githubusercontent.com/34529345/125196396-6142d200-e28c-11eb-9449-2716bb84e2a7.png)

**Comment by kwea123** [comment]
OK, so If the code part is the same, then the problem can only come from the data. Do you use the preprocessed data https://github.com/kwea123/CasMVSNet_pl#data-download? Or do you use the original DTU data?

**Comment by YuhsiHu** [comment]
Thanks a lot!
I think the folder named "Rectified" I used is wrong, the pictures in it are 640X512. They should be 1600X1200, right?
What is the architecture of your training and testing dataset? 
Mine traning dataset is:
**Cameras**
    txt files
**Depths**
   -- scan1
          pfm files
    -- scan2
    -- ... 
**Depths_raw**
   -- scan1
          pfm files
    -- scan2
    -- ... 
**Rectified**
    -- scan1
          png files
    -- scan2
    -- ... 

And when traning, I think the code use pictures in Rectified, which is different from original cascade-MVSNet.

**Comment by kwea123** [comment]
I think almost everyone in this field uses MVSNet's preprocessed files, including me. So in `Depths` and `Rectified`, there are folders named `scanXX_train`, these contain images of size 640x512, and are images that are used in training.
I forgot what `Depth_raw` is, but it seems it's not used for training (and testing).

So I'm very confused as it seems that the data you use is the same as mine, I don't understand why there is still difference...

**Comment by YuhsiHu** [comment]
When testing, do we need to use DTU testing data from [MVSNet-pytorch](https://github.com/xy-guo/MVSNet_pytorch)? The images in dataset are 1600X1200. Or we just use the data in traning dataset(which is 640X512)?

**Comment by stillwang96** [comment]
Hi,
I am now facing the same problem as you now. Do you have solved it? And by the way, how can I see the tensorboard without a events.out.file?

**Comment by kwea123** [comment]
@YuhsiHu When testing, I read the images and parameters from full size images, you can see the code.
@stillwang96 I don't understand your second question, what do you want to see without a event file?

**Comment by stillwang96** [comment]
The loss curve just as the log1.png and log2.png as your assets show. I don't know how to view the tensorboard. Thank you.

**Comment by kwea123** [comment]
that's just screenshots. When you train, the program will generate .event files under `logs`. Then in another terminal, run `tensorboard --logdir logs` to visualize it. This kind of question is better to ask in stackoverflow. And this is not related to this issue, next time please open a new issue.

**Comment by stillwang96** [comment]
OK, sorry, you mean that just when training I can view the tensorboard, and after trained, I can't view it, right? Or can I save the .event files?

**Comment by YuhsiHu** [comment]
I download the dataset from MVSNet project. The images under dtu_training/Rectified are 640X512, and they have another testing dataset(1600X1200). The structure of testing dataset is: **scanXXX**: **cams**, **images**, **pairs.txt**. But in your eval.py, you read the images under Rectified folders. So I have to replace the images with 1600X1200?

**Comment by frspring** [comment]
It's weired. I'm not sure but it seems I stuck in the same issue from the mvsnerf which is based on this project. ;)

**Comment by xingchen2022** [comment]
> I download the dataset from MVSNet project. The images under dtu_training/Rectified are 640X512, and they have another testing dataset(1600X1200). The structure of testing dataset is: **scanXXX**: **cams**, **images**, **pairs.txt**. But in your dtu.py, you read the images under Rectified folders. So I have to replace the images with 1600X1200?

Though this issue is reported a long time ago, for anyone else who may encounter a similar problem, I think this is the solution. i.e. when testing we use 1600x1200 image(Recitified_raw folder) and will crop it to 1152x864 (args.img_wh), instead of 640x512 image(Recitified folder) which will be resized to 1152x864 by  opencv's bilinear interpolation.

I got  28.88M points with 1600x1200 image and  only 15.72M points with 640x512 image.

**Comment by YuhsiHu** [comment]
> > I download the dataset from MVSNet project. The images under dtu_training/Rectified are 640X512, and they have another testing dataset(1600X1200). The structure of testing dataset is: **scanXXX**: **cams**, **images**, **pairs.txt**. But in your dtu.py, you read the images under Rectified folders. So I have to replace the images with 1600X1200?
> 
> Though this issue is reported a long time ago, for anyone else who may encounter a similar problem, I think this is the solution. i.e. when testing we use 1600x1200 image(Recitified_raw folder) and will crop it to 1152x864 (args.img_wh), instead of 640x512 image(Recitified folder) which will be resized to 1152x864 by opencv's bilinear interpolation.
> 
> I got 28.88M points with 1600x1200 image and only 15.72M points with 640x512 image for scan1.

Exactly. I will close this issue.
