### ISSUE TITLE
question about purpose of scale_factor in blendedmvs.py

### ISSUE THREAD

**Issue by LuckyOne09** [kwea123/CasMVSNet_pl#39]
Hi, thank you very much for your code at first!
I have some questions about ```scale_factor``` used  in ```./datasets/blendedmvs.py```
the locations are:
https://github.com/kwea123/CasMVSNet_pl/blob/5813306b451b22226a321d347e5f6020a20ae8c9/datasets/blendedmvs.py#L98-L103
and
https://github.com/kwea123/CasMVSNet_pl/blob/5813306b451b22226a321d347e5f6020a20ae8c9/datasets/blendedmvs.py#L108
I think you are scaling up the scene in BlendedMVS and I also know the unit in BlendMVS is uncertain.
However, I feel it is not necessary to scale up. I think the essence of CasMVSNet is to find correspondances among multiple views and it only depends on images. Scaling up does not help find correspondances. (I think the depth map is a form of correspondance)

Therefore, I want to know why you think it is necessary and did you see improvements after adding ```scale_factor```?

**Comment by LuckyOne09** [comment]
moreover, why you choose 100/depth_min as scale? I can not figure out the reason. Thank you in advance!

**Comment by kwea123** [comment]
https://github.com/kwea123/CasMVSNet_pl#some-modifications-wrt-original-paper
