### ISSUE TITLE
Results on DTU

### ISSUE THREAD

**Issue by stillwang96** [kwea123/CasMVSNet_pl#40]
Hi, thank you for your contributions first. How can I get the results like abs_err | acc_1mm | acc_2mm | acc_4mm in your project?

**Comment by kwea123** [comment]
In training they are computed here:
https://github.com/kwea123/CasMVSNet_pl/blob/5813306b451b22226a321d347e5f6020a20ae8c9/train.py#L149-L152
If you want to compute them in testing, just borrow this code.
