### ISSUE TITLE
Size mismatch when running with release model trained on BlendedMVS data

### ISSUE THREAD

**Issue by KevinCain** [kwea123/CasMVSNet_pl#8]
While the .ply output I compute using your [release model](https://github.com/kwea123/CasMVSNet_pl/releases/tag/v1.0) have very similar point counts to your .ply model releases, the overall quality is quite different, as shown below. As shown, the former is clearly captures more detail.

@kwea123 , do these results for DTU's scan9 data set look reasonable? I have not changed the default image width/height set in the code (e.g., 1152x864).

I also attempted to run with the release model trained on BlendedMVS data https://github.com/kwea123/CasMVSNet_pl/releases/tag/1.5, but that led to the size mismatch noted below:

**Trained on DTU**: [_ckpt_epoch_10.ckpt](https://github.com/kwea123/CasMVSNet_pl/releases/tag/v1.0)
25.37 M points
![scan9_DTU](https://user-images.githubusercontent.com/5424003/78090863-587d0400-7399-11ea-9026-b9f9b7060185.jpeg)

**Release output**: [Reference model](https://github.com/kwea123/CasMVSNet_pl/releases/tag/v1.2)
25.42 M points
![scan_9_ref](https://user-images.githubusercontent.com/5424003/78090901-70548800-7399-11ea-9238-da20ce16e6f6.jpeg)

**Trained on BlendedMVS**: [epoch.15.ckpt](https://github.com/kwea123/CasMVSNet_pl/releases/tag/1.5)

`RuntimeError: Error(s) in loading state_dict for CascadeMVSNet:
	size mismatch for cost_reg_1.conv0.conv.weight: copying a param with shape torch.Size([8, 8, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([8, 16, 3, 3, 3]).
	size mismatch for cost_reg_2.conv0.conv.weight: copying a param with shape torch.Size([8, 8, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([8, 32, 3, 3, 3]).`

**Comment by kwea123** [comment]
I found where the discrepancy is. When I added tanks and blendedmvs dataset, in order to reduce the RAM consumption during point cloud fusion, I resized the images to 1/4. As a result many details are lost, which makes the visual difference (as seen on the text "ANTIQUITATEN" on the bottom right corner).

I made a quick hardcoded patch just now which disables image resizing for DTU (basically reverted to tag1.2), with that code you can generate the same cloud as me now.

For model trained on blendedmvs you need to add `--depth_interval 192.0 --num_groups 8` for evaluation.

**Comment by KevinCain** [comment]
I can happily confirm that your [initial fix](https://github.com/kwea123/CasMVSNet_pl/commit/5279b7708ea03bdf8d13156ddd234cbcc8682d28) and [refinement](https://github.com/kwea123/CasMVSNet_pl/commit/5279b7708ea03bdf8d13156ddd234cbcc8682d28) both more closely match your provided release .ply sets!

I should have suspected 1/4 scale depths from simply looking at the point cloud.

Thanks for your flag note to invoke with your model trained on BlendedMVS, which is wonderful to see. I see a noticeable decrease in completeness compared with the model trained on DTU data; for example, observe the occluded regions in this snapshot of a scan9 output .ply containing 25.37M points:
![image](https://user-images.githubusercontent.com/5424003/78172260-bfdf9600-7423-11ea-8ecf-68b1adf4d027.png)

In comparison, the model trained on BlendedMVS data, scan9 contains 22.08M points and completeness is reduced in the same occluded regions:
![image](https://user-images.githubusercontent.com/5424003/78172289-cf5edf00-7423-11ea-9082-9696fe7cbb16.png)

Similarly, in the relatively well-sampled area often chosen by authors for paper illustrations, we see this striking difference in completeness -- see first the DTU model results here:
![image](https://user-images.githubusercontent.com/5424003/78172953-f1a52c80-7424-11ea-8ba6-b89d71862407.png)

And next the corresponding BlendedMVS model results:
![image](https://user-images.githubusercontent.com/5424003/78173018-097cb080-7425-11ea-8c83-8c2b9c7b0a9d.png)

Here is an overview (DTU model results at top, BlendedMVS at bottom); note that the best reconstruction area is unsurprisingly the far left building façade, where view neighbors are more fronto-planar to the camera. The quality of the main façade in the center of the image may relate to  nuances of the depth fusion implementation, rather than the depth inferences themselves. Overall the boundaries may be better behaved with the model trained with BlendedMVS data, as Yao Yao's paper suggests:

![comp](https://user-images.githubusercontent.com/5424003/78173919-73498a00-7426-11ea-8a5b-b546e1786ba0.jpeg)
